export const PROJECT_DETAIL_PHONE_WIDTH = "19.25rem";
export const PROJECT_DETAIL_PHONE_HEIGHT = "44rem";

export const PROJECT_DETAIL_OLDER_RELEASES = 3;
export const PROJECT_DETAIL_RELEASE_COUNT = 1 + PROJECT_DETAIL_OLDER_RELEASES;

export const PROJECT_DETAIL_RELEASES_PER_PAGE = 10;

export const PROJECT_DETAIL_COPY_FEEDBACK_MS = 1500;
